# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SRS_Native' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SRS_Native

pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'LayoutHelper'
pod 'Toaster'
pod 'KeychainSwift', '~> 19.0'


end
